# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b7d56ed4f84f64fa0ea60fb39f224ecf3210042135e12272ee3a6248ace00adb031a521f6997d802b5b73f0e31c9a3051d49375031c77f1721539589579b657

test:
  secret_key_base: 75ad42466cf0dc904cd7b7b541ab7583a7fc78b2a75b44dafd11e8c4356f927d97295e4a12f87aaf332dbe655c4ebfca733b0d5e406d1d673b5b882ee4d79741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
